/*
  Seed ALL provider trade exam answer keys (14 trades x 20 questions).
  Table: dbo.IndorProveedorExamPreguntas
    - CorrectIndex is ZERO-BASED (0 = first option in OptionsJson).
    - Use vw_IndorProveedorExamAnswerKey to read the correct answer text.

  Prerequisite: CreateProviderPortalTables.sql (creates IndorProveedorExamPreguntas
  and IndorProveedorExamRespuestas for storing each provider''s submitted answers).

  Trades: electrical, plumbing, hvac, handyman, construction, bathroom, kitchen,
          roofing, painting, flooring, cleaning, landscaping, pest, appliance
*/
SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.IndorProveedorExamPreguntas', N'U') IS NULL
BEGIN
    RAISERROR('Run CreateProviderPortalTables.sql first.', 16, 1);
    RETURN;
END
GO

DELETE FROM dbo.IndorProveedorExamPreguntas;
GO

INSERT INTO dbo.IndorProveedorExamPreguntas (TradeCode, QuestionNumber, PageNumber, TextEn, OptionsJson, CorrectIndex) VALUES(N'electrical', 1, 1, N'Which breaker size should match the circuit load and wire rating?', N'["The smallest breaker available","The breaker one size larger than the wire","The breaker that matches the wire ampacity","The largest breaker available"]', 2),
(N'electrical', 2, 1, N'Before replacing a receptacle, what should be done first?', N'["Test for voltage","Remove the wall plate","Turn off the circuit","Disconnect the neutral wire"]', 2),
(N'electrical', 3, 1, N'What is the minimum working clearance in front of an electrical panel rated 600V or less?', N'["24 inches (600 mm)","36 inches (900 mm)","30 inches (750 mm)","42 inches (1050 mm)"]', 1),
(N'electrical', 4, 1, N'Which of the following is the correct order for lockout/tagout?', N'["Lockout, verify, tagout","Notify, lockout, verify, tagout","Tagout, lockout, verify","Lockout, tagout, verify"]', 1),
(N'electrical', 5, 2, N'Which wire type is commonly used for indoor branch circuit wiring in residential work?', N'["Bare copper grounding wire only","NM-B cable","Flexible extension cord","Low-voltage thermostat wire"]', 1),
(N'electrical', 6, 2, N'What device is required to protect receptacles in bathrooms?', N'["Standard breaker","GFCI protection","Surge protector","Fuse only"]', 1),
(N'electrical', 7, 2, N'What is the main purpose of bonding metal electrical parts?', N'["Increase voltage","Provide a safe fault path","Reduce wire size","Lower utility bills"]', 1),
(N'electrical', 8, 2, N'What should be verified after installing a new breaker?', N'["Paint color","Correct fit, rating, and operation","Panel label only","Only that the cover closes"]', 1),
(N'electrical', 9, 3, N'Which receptacle type is typically required in a garage?', N'["Ungrounded two-slot","GFCI-protected receptacle","240V dryer outlet","Telephone jack"]', 1),
(N'electrical', 10, 3, N'What must be done before working inside an energized panel?', N'["Nothing if the job is quick","Wear PPE and follow safe procedures","Stand on concrete barefoot","Use a plastic hammer"]', 1),
(N'electrical', 11, 3, N'What does AFCI protection help reduce?', N'["Water leaks","Arc-fault fire risk","Low water pressure","Paint damage"]', 1),
(N'electrical', 12, 3, N'What is the purpose of a service disconnect?', N'["Decorate the panel","Shut off power to the service","Boost current","Replace a transformer"]', 1),
(N'electrical', 13, 4, N'What is the safest way to confirm a circuit is de-energized?', N'["Touch the wire quickly","Ask someone else","Use an approved tester or meter","Look at the light switch"]', 2),
(N'electrical', 14, 4, N'Why are electrical panels required to be clearly labeled?', N'["For decoration","To identify circuits and improve safety","To increase voltage","To hide spare breakers"]', 1),
(N'electrical', 15, 4, N'Which area commonly requires weather-resistant devices outdoors?', N'["Attic only","Exterior receptacles","Closet shelving","Interior bedrooms"]', 1),
(N'electrical', 16, 4, N'What is one sign that a receptacle may need replacement?', N'["It holds plugs tightly","Cracks, heat, or loose connections","The wall is painted","The cover plate is white"]', 1),
(N'electrical', 17, 5, N'What should be checked before replacing a light fixture?', N'["Only the paint color","The homeowner''s furniture","Voltage, mounting support, and circuit condition","Internet speed"]', 2),
(N'electrical', 18, 5, N'What is the main function of a grounding conductor?', N'["Carry normal load current","Increase appliance speed","Provide a path for fault current","Reduce room lighting"]', 2),
(N'electrical', 19, 5, N'If an electrical box is overfilled, what is the risk?', N'["Better cooling","Faster installation","Loose or damaged conductors","Lower ampacity demand"]', 2),
(N'electrical', 20, 5, N'After finishing the exam, what unlocks job eligibility?', N'["Submitting any photo","Choosing multiple trades","Passing the exam and completing verification","Skipping the license upload"]', 2),
(N'plumbing', 1, 1, N'Before repairing a leaking supply line, what should be done first?', N'["Shut off the water supply","Replace the faucet handle","Open all drains","Increase water pressure"]', 0),
(N'plumbing', 2, 1, N'What is the best reason to verify pipe material before making a repair?', N'["To match fittings and repair method correctly","To increase water flow","To skip inspection","To avoid using tools"]', 0),
(N'plumbing', 3, 1, N'What tool is commonly used to tighten a compression fitting?', N'["Adjustable wrench","Paint brush","Voltage tester","Caulk gun"]', 0),
(N'plumbing', 4, 1, N'If a drain is slow but not completely blocked, what is usually the first basic troubleshooting step?', N'["Inspect and clear the trap or stopper area","Cut the pipe immediately","Replace the water heater","Increase supply pressure"]', 0),
(N'plumbing', 5, 2, N'What is the main purpose of a P-trap under a sink?', N'["To prevent sewer gases from entering the home","To increase water pressure","To cool the water","To hold extra tools"]', 0),
(N'plumbing', 6, 2, N'When soldering copper pipe, what must be done before applying solder?', N'["Clean and flux the joint","Fill the pipe with water","Paint the fitting","Tighten with a hammer"]', 0),
(N'plumbing', 7, 2, N'What is the safest first step before removing a toilet supply valve?', N'["Shut off the water and relieve pressure","Open the water heater drain","Cut the wall open","Install a new faucet"]', 0),
(N'plumbing', 8, 2, N'What is a common sign of a hidden water leak?', N'["Unexpected increase in water bill","Brighter light bulbs","Faster internet speed","Lower ceiling height"]', 0),
(N'plumbing', 9, 3, N'What should be used to seal threaded pipe connections in many basic plumbing installations?', N'["Thread seal tape or approved pipe compound","Wood glue","Spray paint","Dry paper towel"]', 0),
(N'plumbing', 10, 3, N'Why is pipe slope important on a drain line?', N'["It helps wastewater flow properly","It increases electrical voltage","It makes the pipe colder","It eliminates all venting needs"]', 0),
(N'plumbing', 11, 3, N'Before replacing a water heater, what should be confirmed first?', N'["Fuel type, size, and code requirements","Paint color in the room","Wi-Fi password","Number of windows nearby"]', 0),
(N'plumbing', 12, 3, N'What is the purpose of a shutoff valve at a fixture?', N'["To isolate water to that fixture for service","To increase drain speed","To vent sewer gas","To hold water permanently"]', 0),
(N'plumbing', 13, 4, N'If a customer reports low water pressure at only one faucet, what is a reasonable first check?', N'["Inspect the aerator for blockage","Replace the entire water main","Raise house temperature","Remove the roof vent"]', 0),
(N'plumbing', 14, 4, N'What is the function of a plumbing vent?', N'["It allows air into the system for proper drainage","It heats the drain pipe","It seals water lines shut","It replaces the need for traps"]', 0),
(N'plumbing', 15, 4, N'When using PVC solvent cement, what is important before assembly?', N'["Use the correct cleaner or primer when required","Soak the pipe in oil","Wait until the pipe is full of water","Hammer the fitting into place"]', 0),
(N'plumbing', 16, 4, N'What should be done after completing a small repair on a supply line?', N'["Restore water and check carefully for leaks","Cover the repair immediately with insulation only","Increase pressure beyond normal","Leave the valve off forever"]', 0),
(N'plumbing', 17, 5, N'What is one reason plumbers verify local code requirements before a replacement job?', N'["To ensure the installation meets required standards","To avoid using measurements","To skip permits automatically","To reduce water quality"]', 0),
(N'plumbing', 18, 5, N'What is a common use of a basin wrench?', N'["Tightening or loosening faucet nuts in tight spaces","Cutting ceramic tile","Testing electrical circuits","Cleaning roof shingles"]', 0),
(N'plumbing', 19, 5, N'Which situation usually requires urgent plumbing attention?', N'["An active burst pipe leak","A loose doormat","A dim hallway light","A squeaky door hinge"]', 0),
(N'plumbing', 20, 5, N'After finishing the plumbing exam, what happens next in this onboarding flow?', N'["INDOR reviews the exam and verification documents","The provider can immediately select every service category","The app deletes the profile automatically","No review is needed"]', 0),
(N'hvac', 1, 1, N'Before servicing an HVAC unit, what should be done first?', N'["Disconnect power and verify it is off","Open the refrigerant valves","Replace the thermostat","Increase fan speed"]', 0),
(N'hvac', 2, 1, N'What is the main purpose of an air filter?', N'["Protect equipment and improve airflow quality","Raise refrigerant pressure","Increase compressor voltage","Lubricate the blower motor"]', 0),
(N'hvac', 3, 1, N'Which tool is commonly used to check voltage?', N'["Multimeter","Pipe cutter","Manifold hose only","Thermometer"]', 0),
(N'hvac', 4, 1, N'If the thermostat screen is blank, what should be checked first?', N'["Power supply or batteries","Compressor oil","Condenser coil color","Duct insulation"]', 0),
(N'hvac', 5, 2, N'A dirty evaporator coil most commonly causes?', N'["Reduced cooling performance","Higher thermostat accuracy","Increased refrigerant recovery","Stronger breaker protection"]', 0),
(N'hvac', 6, 2, N'Low airflow across the evaporator can lead to?', N'["Coil icing","Higher gas pressure only","Larger duct size","Automatic refrigerant refill"]', 0),
(N'hvac', 7, 2, N'A common cause of short cycling is?', N'["Dirty filter or thermostat issue","Fresh paint on walls","Oversized shoes on the installer","Low ladder height"]', 0),
(N'hvac', 8, 2, N'When some rooms are much warmer than others, what should be checked?', N'["Airflow, ducts, and dampers","Roof color only","Water heater settings","Exterior brick pattern"]', 0),
(N'hvac', 9, 3, N'Before adding refrigerant, what should a technician do first?', N'["Verify charge and check for leaks","Open the condensate drain","Replace the thermostat immediately","Shut off the furnace gas valve"]', 0),
(N'hvac', 10, 3, N'Symptoms such as low pressure and poor cooling may suggest?', N'["Possible low refrigerant charge","Perfect system balance","Too much duct insulation","An upgraded air filter only"]', 0),
(N'hvac', 11, 3, N'Why are superheat and subcooling checked?', N'["To verify system charge and performance","To estimate property taxes","To repaint the condenser","To reset Wi-Fi"]', 0),
(N'hvac', 12, 3, N'Refrigerant must be recovered using?', N'["Approved recovery equipment","A garden hose","An open bucket","A vacuum cleaner"]', 0),
(N'hvac', 13, 4, N'A failed capacitor may cause?', N'["Motor not starting properly","More refrigerant in the lines","Higher home resale value","A larger air filter"]', 0),
(N'hvac', 14, 4, N'What component protects the compressor from high pressure?', N'["High-pressure switch","Drain pan only","Thermostat cover","Blower wheel"]', 0),
(N'hvac', 15, 4, N'If the condenser fan is not running, what should be checked first?', N'["Power, contactor, and capacitor","Grass height outside","Kitchen sink pressure","Window blinds"]', 0),
(N'hvac', 16, 4, N'What is the purpose of a contactor?', N'["It switches high-voltage power using a control signal","It cleans the evaporator coil","It stores condensate water","It measures duct insulation"]', 0),
(N'hvac', 17, 5, N'What should be documented after service is completed?', N'["Work performed, readings, and recommendations","Only the customer''s ZIP code","Paint color of the unit","Nothing if the job was simple"]', 0),
(N'hvac', 18, 5, N'When should a condensate drain issue be addressed?', N'["Immediately to avoid water damage","Next year during repainting","Only in winter","After replacing the roof"]', 0),
(N'hvac', 19, 5, N'If a major safety concern is found, what is the best action?', N'["Inform the customer clearly and make the system safe","Ignore it and leave","Raise the refrigerant charge","Change the thermostat color"]', 0),
(N'hvac', 20, 5, N'What helps extend HVAC system life?', N'["Regular maintenance and filter changes","Closing every vent","Running the system without a filter","Skipping inspections"]', 0),
(N'handyman', 1, 1, N'Before drilling into a wall, what should be checked first?', N'["Hidden wires or pipes","Window height","Paint color","Floor finish"]', 0),
(N'handyman', 2, 1, N'What is the best way to prepare a surface before applying new caulk?', N'["Clean it and remove old caulk","Apply new caulk over dirt","Wet the surface","Skip preparation"]', 0),
(N'handyman', 3, 1, N'When hanging a heavy shelf, what provides the safest support?', N'["Wall studs or proper anchors","Tape only","Thumbtacks","Small finish nails only"]', 0),
(N'handyman', 4, 1, N'What should be done before patching a damaged drywall hole?', N'["Remove loose material and clean the area","Add water only","Paint first","Ignore cracked edges"]', 0),
(N'handyman', 5, 2, N'When mounting a TV bracket, what is the safest fastening method?', N'["Secure it into wall studs","Use glue only","Use push pins","Hang it from trim"]', 0),
(N'handyman', 6, 2, N'Which tool is best for checking whether a shelf is straight?', N'["Level","Hammer","Paint brush","Pliers"]', 0),
(N'handyman', 7, 2, N'Before removing a door hinge, what helps prevent the door from falling?', N'["Support the door","Paint the frame","Open a window","Loosen every screw at once"]', 0),
(N'handyman', 8, 2, N'After applying joint compound to a wall patch, what usually comes next before painting?', N'["Let it dry and sand it smooth","Wash it with soap","Install anchors","Apply grout"]', 0),
(N'handyman', 9, 3, N'What is the proper first step when a customer reports loose cabinet hardware?', N'["Inspect the screws and mounting points","Paint the cabinet","Replace the countertop","Ignore the issue"]', 0),
(N'handyman', 10, 3, N'What is the safest first step before replacing a light fixture?', N'["Turn off the breaker and verify power is off","Remove the bulbs only","Touch the wires carefully","Spray the fixture with water"]', 0),
(N'handyman', 11, 3, N'For a small hole in drywall, what repair material is commonly used?', N'["Spackle or patch compound","Roof shingles","Concrete mix","Plumbing putty"]', 0),
(N'handyman', 12, 3, N'When resealing around a bathtub, what condition should the area be in before new caulk is applied?', N'["Clean and completely dry","Wet and soapy","Covered in dust","Freshly painted"]', 0),
(N'handyman', 13, 4, N'What anchor type is commonly used when mounting into drywall without a stud?', N'["A drywall anchor rated for the load","A paper clip","A carpet tack","A zip tie"]', 0),
(N'handyman', 14, 4, N'When trimming a piece of baseboard for an inside corner, what tool is often used for a clean angled cut?', N'["Miter saw or miter box","Pipe wrench","Garden shovel","Stapler"]', 0),
(N'handyman', 15, 4, N'What is the best response if a repair request is beyond your skill or licensing scope?', N'["Explain the limitation and recommend the proper specialist","Attempt it anyway","Hide the problem","Charge extra and guess"]', 0),
(N'handyman', 16, 4, N'Before using a ladder indoors, what should be confirmed?', N'["It is on a firm, level surface and fully opened","It is leaning on a chair","It is placed on a rug edge","It is missing a foot"]', 0),
(N'handyman', 17, 5, N'What is a common fix for a squeaky interior door?', N'["Lubricate the hinge pins","Cut the frame","Replace the floor","Turn off the water"]', 0),
(N'handyman', 18, 5, N'What should be checked before installing wall-mounted hardware in a bathroom?', N'["Wall type, moisture exposure, and secure fastening","Only the mirror size","Only the paint color","Nothing, install immediately"]', 0),
(N'handyman', 19, 5, N'What is the best way to repair a loose towel bar bracket?', N'["Re-anchor it securely to solid backing or proper anchors","Add soap around it","Use tape only","Ignore the loose mount"]', 0),
(N'handyman', 20, 5, N'Why is it important to protect the work area before a repair?', N'["To avoid damage and keep the customer''s home clean","To hide tools","To make the job slower","To reduce lighting"]', 0),
(N'construction', 1, 1, N'What should be reviewed before starting a remodel project on site?', N'["Project plans and scope","Client''s furniture","Paint colors only","Only the final invoice"]', 0),
(N'construction', 2, 1, N'What is the main purpose of a site safety meeting?', N'["Review hazards and safety expectations","Set decoration ideas","Choose lunch breaks","Discuss marketing"]', 0),
(N'construction', 3, 1, N'Why is it important to verify measurements before ordering materials?', N'["To reduce waste and avoid delays","To skip estimating","To make the project longer","To increase change orders"]', 0),
(N'construction', 4, 1, N'Who is responsible for checking that subcontractors understand the work scope?', N'["The site supervisor or project manager","The material supplier","The homeowner''s neighbor","The painter only"]', 0),
(N'construction', 5, 2, N'What is the best reason to document job progress with photos?', N'["To track work and keep records","To replace permits","To avoid communication","To skip inspections"]', 0),
(N'construction', 6, 2, N'What should be confirmed before demolition begins?', N'["Utilities are identified or shut off as needed","Only the flooring color","The landscaping plan","The social media post"]', 0),
(N'construction', 7, 2, N'Why is a written change order important?', N'["It documents scope, price, and approval changes","It eliminates the contract","It replaces the permit","It delays all work"]', 0),
(N'construction', 8, 2, N'When coordinating multiple trades, what is most important?', N'["Scheduling work in the correct sequence","Letting all trades arrive at once","Ignoring material lead times","Skipping supervision"]', 0),
(N'construction', 9, 3, N'What does a permit generally help confirm?', N'["That the work is approved under local rules","That the owner chose the cheapest option","That tools are new","That no inspection is needed"]', 0),
(N'construction', 10, 3, N'What is the main purpose of a project schedule?', N'["To organize tasks, timing, and coordination","To decorate the jobsite","To replace the estimate","To avoid ordering materials"]', 0),
(N'construction', 11, 3, N'Before pouring concrete or closing walls, what should usually happen?', N'["Required inspections should be completed","The final payment should be collected","The warranty should start","The appliances should be installed"]', 0),
(N'construction', 12, 3, N'What is a good practice when receiving materials on site?', N'["Check delivery quantities and condition","Leave materials in the street","Ignore damaged items","Use them without review"]', 0),
(N'construction', 13, 4, N'What is a common role of the general contractor on a residential remodel?', N'["Coordinate trades and project execution","Only order paint supplies","Skip safety planning","Avoid client communication"]', 0),
(N'construction', 14, 4, N'Why should subcontractors provide proof of insurance?', N'["To reduce liability and verify coverage","To replace permits","To avoid scheduling","To skip inspections"]', 0),
(N'construction', 15, 4, N'What should be done if a structural concern is discovered during construction?', N'["Stop work and evaluate with qualified professionals","Continue without telling anyone","Paint over the issue","Skip documentation"]', 0),
(N'construction', 16, 4, N'Before drywall installation, what should typically be complete?', N'["Framing, rough-ins, and required inspections","Final paint color selection only","Landscaping","Furniture delivery"]', 0),
(N'construction', 17, 5, N'What should be checked before final walkthrough with the client?', N'["Punch list items and completion status","Only the company logo","The next job address","The crew lunch order"]', 0),
(N'construction', 18, 5, N'Why is housekeeping important on a construction site?', N'["It helps reduce trip hazards and keep the site organized","It increases project cost","It replaces PPE","It eliminates scheduling"]', 0),
(N'construction', 19, 5, N'What is a punch list?', N'["A list of remaining corrections or incomplete items","A permit application","A demolition checklist only","A labor timesheet"]', 0),
(N'construction', 20, 5, N'What is the best reason to keep project records organized?', N'["To support communication, billing, and accountability","To avoid supervision","To skip documentation","To reduce safety meetings"]', 0),
(N'bathroom', 1, 1, N'Before bathroom demolition begins, what should be done first?', N'["Shut off water and power to the work area","Remove the vanity mirror","Start breaking floor tile","Open the bathroom window"]', 0),
(N'bathroom', 2, 1, N'What is the main purpose of waterproofing behind shower tile?', N'["Prevent water intrusion into walls and subfloor","Improve paint adhesion","Make grout dry faster","Reduce the cost of tile"]', 0),
(N'bathroom', 3, 1, N'Which tool is best for checking whether a wall is plumb before tile installation?', N'["Level","Tape measure","Utility knife","Caulk gun"]', 0),
(N'bathroom', 4, 1, N'When removing an old toilet, what component should be replaced if it is worn or damaged?', N'["Wax ring","Shower valve","Vanity top","Medicine cabinet"]', 0),
(N'bathroom', 5, 2, N'What should be verified before installing a new vanity?', N'["Plumbing shutoffs and wall condition","Only the paint color","The ceiling fan brand","The door hardware"]', 0),
(N'bathroom', 6, 2, N'When cutting tile for a shower niche, what tool is commonly used?', N'["Tile wet saw or appropriate tile cutter","Wood chisel only","Hammer and nails","Spray foam gun"]', 0),
(N'bathroom', 7, 2, N'Why should expansion joints be considered in large tile floors?', N'["To allow for movement and help prevent cracking","To eliminate grout","To speed up drying only","To avoid using spacers"]', 0),
(N'bathroom', 8, 2, N'What helps protect tub and shower surfaces during construction?', N'["Protective coverings over finished surfaces","Leaving tools on the edge","Skipping cleanup","Painting before tile cure"]', 0),
(N'bathroom', 9, 3, N'What is the purpose of a properly sloped shower pan or floor?', N'["To direct water toward the drain","To keep the room warmer","To make tile shine more","To reduce grout joints"]', 0),
(N'bathroom', 10, 3, N'Which material is commonly used to seal the joint between a tub or shower and wall finish?', N'["Silicone caulk","Wood filler","Drywall mud","Spray paint"]', 0),
(N'bathroom', 11, 3, N'Why is it important to inspect the wall studs after demolition?', N'["To confirm the framing is sound and ready for new finishes","To see if mirrors can be reused only","To make the room look bigger","To skip waterproofing"]', 0),
(N'bathroom', 12, 3, N'Before installing a new bathroom exhaust fan, what should be verified?', N'["Proper electrical supply and venting path to the exterior","The color of the light bulbs","The faucet finish","The shower curtain size"]', 0),
(N'bathroom', 13, 4, N'Why should the notched trowel size match the tile being installed?', N'["For proper mortar coverage and bond","To change the tile color","To lower the ceiling height","To replace grout"]', 0),
(N'bathroom', 14, 4, N'Where should a toilet flange ideally finish after the bathroom floor is completed?', N'["On top of the finished floor","Below the subfloor","Behind the vanity","Inside the wall cavity"]', 0),
(N'bathroom', 15, 4, N'Before grouting newly installed tile, what is the best practice?', N'["Let the setting material cure according to manufacturer instructions","Apply grout immediately while mortar is wet","Remove all spacers and flood the floor with water","Polish the tile with wax"]', 0),
(N'bathroom', 16, 4, N'If subfloor water damage is discovered during a remodel, what should be done?', N'["Repair or replace the damaged area before finishing the installation","Cover it with tile and continue","Paint over it","Ignore it if the vanity hides it"]', 0),
(N'bathroom', 17, 5, N'Why is GFCI protection important for bathroom receptacles?', N'["To help protect people from electrical shock near water","To increase water pressure","To dry grout faster","To replace the wax ring"]', 0),
(N'bathroom', 18, 5, N'Before final project handoff, what should be tested and checked?', N'["Fixtures, drainage, and finishes","Only the company logo","The next job address","The crew lunch order"]', 0),
(N'bathroom', 19, 5, N'What is the best way to protect the homeowner''s property during a bathroom remodel?', N'["Use floor protection and keep the work area clean","Leave materials in walkways","Skip daily cleanup","Open all windows only"]', 0),
(N'bathroom', 20, 5, N'If the project scope changes after work begins, what should the contractor do?', N'["Discuss and document changes with the customer","Continue without telling anyone","Skip written approval","Change the price silently"]', 0),
(N'kitchen', 1, 1, N'Before removing old cabinets, what should be done first?', N'["Cut the new countertops","Shut off utilities in the work area","Install backsplash","Paint the walls"]', 1),
(N'kitchen', 2, 1, N'Why is it important to confirm final kitchen measurements before ordering cabinets?', N'["To reduce demolition dust","To make sure cabinets fit the layout correctly","To avoid checking wall condition","To skip appliance planning"]', 1),
(N'kitchen', 3, 1, N'Which item should be protected before demolition begins?', N'["Exposed wiring only","Floors and nearby finished areas","Cabinet hardware only","Empty cardboard boxes"]', 1),
(N'kitchen', 4, 1, N'When planning a kitchen layout, what should be verified early?', N'["The music playlist","Appliance sizes and placement","The paint brand only","The final cleaning date"]', 1),
(N'kitchen', 5, 2, N'What is the main purpose of a kitchen work triangle?', N'["To choose paint colors","To improve movement between sink, stove, and refrigerator","To reduce countertop thickness","To select cabinet hardware"]', 1),
(N'kitchen', 6, 2, N'Before installing new base cabinets, what must be checked?', N'["That the floor is level","That the backsplash is finished first","That the windows are open","That the refrigerator is running"]', 0),
(N'kitchen', 7, 2, N'Why should backsplash and countertop selections be coordinated early?', N'["To avoid checking measurements","To make sure finishes and fit work together","To increase demolition time","To skip cabinet layout review"]', 1),
(N'kitchen', 8, 2, N'When replacing kitchen lighting, what is most important first?', N'["Matching the music playlist","Confirming safe electrical planning and fixture placement","Buying paint rollers","Ordering bar stools"]', 1),
(N'kitchen', 9, 3, N'Why is it important to verify rough plumbing and electrical locations before cabinet installation?', N'["So cabinets and appliances fit without conflicts","So flooring can be skipped","So drywall never needs repair","So paint can be chosen faster"]', 0),
(N'kitchen', 10, 3, N'What should be done before templating for countertops?', N'["Cabinets should be installed and secured in place","The final cleaning should be finished","Appliances should be removed from the store box only","The backsplash should already be grouted"]', 0),
(N'kitchen', 11, 3, N'What is a key reason to protect adjacent rooms during demolition?', N'["To keep dust and debris from spreading","To avoid ordering cabinets","To change the sink style","To increase labor time"]', 0),
(N'kitchen', 12, 3, N'When installing cabinets, why are shims commonly used?', N'["To decorate open shelves","To level and align cabinets properly","To waterproof countertops","To hide plumbing leaks"]', 1),
(N'kitchen', 13, 4, N'What is the best reason to review appliance specifications before finalizing the design?', N'["To ensure openings, utility needs, and clearances are correct","To choose wall paint first","To reduce the number of cabinet doors","To avoid checking ventilation"]', 0),
(N'kitchen', 14, 4, N'When setting wall cabinets, what should be confirmed first?', N'["That upper cabinet height and support attachment points are correct","That the floor tile is already sealed","That the garbage disposal is plugged in","That the stools match the island color"]', 0),
(N'kitchen', 15, 4, N'Why should ventilation be considered in a kitchen remodel?', N'["To improve removal of heat, smoke, and cooking odors","To make cabinet doors heavier","To lower backsplash height","To avoid measuring the range"]', 0),
(N'kitchen', 16, 4, N'What is a good practice before starting finish work and punch-out?', N'["Ignore minor defects","Inspect surfaces, alignments, and hardware function","Remove all appliance manuals","Skip testing lights and outlets"]', 1),
(N'kitchen', 17, 5, N'Why is waterproofing around sink and splash areas important?', N'["To protect surrounding materials from moisture damage","To reduce cabinet storage","To select paint brushes","To avoid measuring the countertop"]', 0),
(N'kitchen', 18, 5, N'Before turning over a completed kitchen remodel, what should be tested?', N'["Appliances, lights, outlets, plumbing fixtures, and cabinet hardware","Only the paint color in daylight","Only the broom closet door","Only the countertop edge color"]', 0),
(N'kitchen', 19, 5, N'What is the purpose of a final walkthrough with the customer?', N'["To review completed work, confirm function, and note any punch-list items","To skip documentation","To remove all labels before inspection","To choose a new sink color after installation"]', 0),
(N'kitchen', 20, 5, N'What is the best reason for maintaining a clean and organized jobsite during the remodel?', N'["To improve safety, efficiency, and customer confidence","To make demolition louder","To avoid using protective coverings","To reduce layout accuracy"]', 0),
(N'roofing', 1, 1, N'What should a roofer check first before accessing a roof?', N'["Ladder condition and fall protection","Interior flooring","Paint color of the house","Mailbox location"]', 0),
(N'roofing', 2, 1, N'What is the main purpose of flashing around roof penetrations?', N'["Prevent water intrusion","Decorate the roof","Increase roof weight","Reduce attic storage"]', 0),
(N'roofing', 3, 1, N'A lifted or missing shingle most commonly increases the risk of:', N'["Water leaks and wind damage","Stronger ventilation","Lower utility bills","Bigger gutters"]', 0),
(N'roofing', 4, 1, N'What do ridge and soffit vents help improve?', N'["Attic airflow","Window insulation","Driveway drainage","Cabinet installation"]', 0),
(N'roofing', 5, 2, N'When tracing a roof leak from an interior stain, where should the inspection usually begin?', N'["Upslope from the stain","At the mailbox","Inside kitchen cabinets","At the driveway edge"]', 0),
(N'roofing', 6, 2, N'A damaged pipe boot most often causes leaks around:', N'["Vent pipe penetrations","Window blinds","Concrete slabs","Fence posts"]', 0),
(N'roofing', 7, 2, N'Excessive shingle granule loss is commonly a sign of:', N'["Aging or impact wear","Improved durability","Better attic storage","Lower roof temperature"]', 0),
(N'roofing', 8, 2, N'What is the main purpose of drip edge metal?', N'["Direct water away from the fascia","Hold insulation in place","Increase roof height","Decorate the eaves"]', 0),
(N'roofing', 9, 3, N'Soft or spongy roof decking usually indicates:', N'["Moisture damage or rot","Perfect ventilation","Stronger shingles","Fresh paint"]', 0),
(N'roofing', 10, 3, N'Which fastener is typically appropriate for asphalt shingles?', N'["Roofing nails","Drywall screws","Staples for paper","Wood glue"]', 0),
(N'roofing', 11, 3, N'Where is ice and water shield commonly installed for extra protection?', N'["Valleys and vulnerable eaves","Only on interior walls","Behind kitchen sinks","Around ceiling fans only"]', 0),
(N'roofing', 12, 3, N'On a flat roof, standing water is a concern because it can:', N'["Lead to leaks and membrane wear","Improve insulation","Reduce maintenance forever","Strengthen the roof deck"]', 0),
(N'roofing', 13, 4, N'Step flashing is primarily used where the roof meets a:', N'["Sidewall or chimney","Garage floor","Mailbox post","Driveway curb"]', 0),
(N'roofing', 14, 4, N'A common sign of hail damage on shingles is:', N'["Bruising or impact marks","Bigger gutters","Straighter fence lines","Higher attic shelving"]', 0),
(N'roofing', 15, 4, N'If a shingle is missing after a storm, the best action is to:', N'["Replace and secure it properly","Ignore it for a year","Paint the roof","Open attic windows"]', 0),
(N'roofing', 16, 4, N'Good attic ventilation helps reduce:', N'["Heat and moisture buildup","The number of shingles","Property taxes","Foundation size"]', 0),
(N'roofing', 17, 5, N'Improper nail placement on shingles can lead to:', N'["Leaks and blow-offs","Wider rafters","Better curb appeal","Lower ceilings"]', 0),
(N'roofing', 18, 5, N'Gutter overflow during rain often suggests:', N'["A clog or drainage issue","Extra attic airflow","Perfect roof performance","Stronger underlayment"]', 0),
(N'roofing', 19, 5, N'What is a good customer best practice after a roof inspection?', N'["Document findings and explain recommendations","Promise work outside your scope","Leave without notes","Remove roof vents"]', 0),
(N'roofing', 20, 5, N'Before leaving a completed roofing job, the crew should:', N'["Perform final cleanup and safety check","Scatter leftover nails","Skip material review","Block drainage paths"]', 0),
(N'painting', 1, 1, N'Before painting a wall, what should be done first?', N'["Apply finish coat immediately","Clean and prepare the surface","Install trim pieces","Remove all windows"]', 1),
(N'painting', 2, 1, N'What is the main reason for using painter''s tape?', N'["To speed up drying","To mix paint colors","To protect edges and create clean lines","To make paint shinier"]', 2),
(N'painting', 3, 1, N'Which protective item should be used when sanding painted surfaces?', N'["Flip-flops","Respirator or dust mask","Sunglasses only","Earbuds"]', 1),
(N'painting', 4, 1, N'Why should floors and furniture be covered before painting?', N'["To reduce paint cost","To keep the room cooler","To protect surfaces from splatters and spills","To dry paint faster"]', 2),
(N'painting', 5, 2, N'Which surface issue should be repaired before painting?', N'["Loose paint and cracks","Fresh air","Clean drop cloths","Full paint cans"]', 0),
(N'painting', 6, 2, N'Why is primer often used on patched drywall?', N'["To hide tools","To improve adhesion and even out porosity","To replace sanding","To make paint smell stronger"]', 1),
(N'painting', 7, 2, N'What is the best way to avoid roller lap marks?', N'["Let each strip dry fully first","Roll in random directions only","Keep a wet edge while rolling","Use the driest roller possible"]', 2),
(N'painting', 8, 2, N'When cutting in around trim, what helps produce a cleaner finish?', N'["A good angled brush and steady strokes","A dirty brush","Extra-thick paint blobs","Painting with the lights off"]', 0),
(N'painting', 9, 3, N'What should be done before opening a paint can that has been sitting for a while?', N'["Shake it with the lid off","Clean dust and debris from the lid area","Add water immediately","Throw away the lid"]', 1),
(N'painting', 10, 3, N'Why is stirring paint important before use?', N'["To blend pigments and sheen evenly","To cool the room","To harden the paint","To dry the paint faster"]', 0),
(N'painting', 11, 3, N'Which tool is most commonly used for smooth wall coverage?', N'["Paint roller","Pipe wrench","Tin snips","Crescent wrench"]', 0),
(N'painting', 12, 3, N'What is the main purpose of a drop cloth?', N'["To protect nearby areas from paint","To make walls shinier","To replace masking tape","To measure the room"]', 0),
(N'painting', 13, 4, N'If paint starts peeling soon after application, what is a likely cause?', N'["Poor surface preparation","Too much natural light","Using a clean brush","Protecting the floor"]', 0),
(N'painting', 14, 4, N'What is the benefit of lightly sanding between coats when needed?', N'["It improves smoothness and adhesion","It makes the wall darker","It eliminates the need for cleanup","It replaces primer every time"]', 0),
(N'painting', 15, 4, N'What should a painter do if overspray might affect nearby surfaces?', N'["Mask and protect surrounding areas","Increase spray pressure only","Ignore nearby items","Open the can wider"]', 0),
(N'painting', 16, 4, N'Which practice is best when moving through a customer''s home?', N'["Keep the work area tidy and protected","Leave tools in walkways","Track paint through the house","Block exits with ladders"]', 0),
(N'painting', 17, 5, N'What is the best response if a customer asks about the paint finish being used?', N'["Explain the selected finish clearly and professionally","Guess and move on","Avoid answering","Change the product without notice"]', 0),
(N'painting', 18, 5, N'Why is ventilation important when using many paints or coatings?', N'["It helps reduce fumes and improve safety","It makes brushes heavier","It replaces surface prep","It eliminates all drying time"]', 0),
(N'painting', 19, 5, N'What should be done with brushes and rollers after the job if they will be reused?', N'["Clean them properly according to the product type","Leave them in the sun until hard","Throw them on the floor","Store them full of wet paint"]', 0),
(N'painting', 20, 5, N'Before leaving the jobsite, what final step is most appropriate?', N'["Walk the job with the customer and clean up the area","Leave without checking the work","Hide leftover paint with trash","Remove wall plates after painting is done"]', 0),
(N'flooring', 1, 1, N'What should be checked before installing any flooring?', N'["Subfloor is clean, dry, and level","Appliance warranty","Wall color","Window blinds"]', 0),
(N'flooring', 2, 1, N'Why is leaving an expansion gap important for floating floors?', N'["Allows material to expand and contract","Hides uneven walls","Makes the floor quieter only","Reduces labor cost"]', 0),
(N'flooring', 3, 1, N'Which tool is commonly used to verify a subfloor is level?', N'["Level or straightedge","Pipe wrench","Paint roller","Wet saw"]', 0),
(N'flooring', 4, 1, N'If moisture is too high in the subfloor, what should be done first?', N'["Stop and resolve the moisture issue","Install more adhesive","Nail down faster","Add extra trim"]', 0),
(N'flooring', 5, 2, N'What is the best way to start a room layout?', N'["Measure the room and plan the first row","Open all boxes randomly","Install from the middle without measuring","Cut planks before marking"]', 0),
(N'flooring', 6, 2, N'Why should flooring cartons acclimate to the room?', N'["So material adjusts to site conditions","To make boxes lighter","To change the color","To reduce trim work"]', 0),
(N'flooring', 7, 2, N'What is a common reason to stagger end joints?', N'["Improve appearance and stability","Reduce cleaning time","Eliminate expansion gaps","Avoid underlayment"]', 0),
(N'flooring', 8, 2, N'When cutting flooring indoors, what is most important?', N'["Use PPE and control dust","Work barefoot","Cut without measuring","Leave tools plugged in unattended"]', 0),
(N'flooring', 9, 3, N'What must be verified before installing tile in a wet area?', N'["Proper waterproofing or approved substrate","Ceiling fan size","Cabinet paint color","Appliance brand"]', 0),
(N'flooring', 10, 3, N'Which underlayment function is correct?', N'["Helps with support, moisture, or sound depending on product","Replaces subfloor repairs","Prevents all movement forever","Eliminates need for layout"]', 0),
(N'flooring', 11, 3, N'For glue-down flooring, why is trowel size important?', N'["It controls adhesive spread rate","It changes board color","It removes need for rolling","It replaces expansion gaps"]', 0),
(N'flooring', 12, 3, N'Before installing hardwood planks, the installer should:', N'["Check moisture content of wood and subfloor","Turn on all faucets","Remove all baseboards forever","Skip site inspection"]', 0),
(N'flooring', 13, 4, N'What is the main purpose of a transition strip?', N'["Create a clean change between floor surfaces or heights","Hold cabinets in place","Waterproof every room","Replace baseboard"]', 0),
(N'flooring', 14, 4, N'If a plank is damaged during install, what should the installer do?', N'["Replace it before finishing the floor","Hide it under a rug","Glue it and continue if cracked","Ignore it"]', 0),
(N'flooring', 15, 4, N'In customer areas, the worksite should be kept:', N'["Clean, protected, and safe to walk through","Loud and crowded","Full of loose nails","Open to children"]', 0),
(N'flooring', 16, 4, N'What should be done after finishing an installation?', N'["Inspect the floor and review care instructions with the customer","Leave scrap everywhere","Remove receipts only","Tell customer not to ask questions"]', 0),
(N'flooring', 17, 5, N'Which direction is often preferred when laying planks in a narrow room?', N'["A planned layout that fits the room and light direction","Always the shortest wall no matter what","Random direction with no plan","Toward the door only"]', 0),
(N'flooring', 18, 5, N'If the final row will be too narrow, the installer should:', N'["Adjust the starting row so first and last rows balance","Force narrow pieces into place","Skip the final row","Add more adhesive"]', 0),
(N'flooring', 19, 5, N'Why is it important to check manufacturer installation instructions?', N'["Products have specific requirements and warranty rules","To avoid measuring","To skip acclimation","All floors install the same way"]', 0),
(N'flooring', 20, 5, N'What is best practice when handing over the finished flooring job?', N'["Confirm completion, cleanup, care guidance, and any next steps","Leave without speaking","Ask customer to clean debris","Promise repairs without inspection"]', 0),
(N'cleaning', 1, 1, N'Before mixing a cleaning chemical, what should you do first?', N'["Read the label and dilution instructions","Mix all products together","Use hot water automatically","Spray directly on surfaces"]', 0),
(N'cleaning', 2, 1, N'What is the safest order when cleaning a bathroom?', N'["Remove trash first","Use the same cloth on every surface","Start with the toilet first every time","Skip gloves to work faster"]', 0),
(N'cleaning', 3, 1, N'Which product should generally be avoided on natural stone?', N'["Acidic cleaner","Microfiber cloth","pH-neutral cleaner","Warm water"]', 0),
(N'cleaning', 4, 1, N'What should be done before vacuuming a room?', N'["Pick up large debris and inspect the floor","Close all vents","Spray bleach on carpet","Mop first"]', 0),
(N'cleaning', 5, 2, N'What helps prevent cross-contamination while cleaning?', N'["Use color-coded cloths by area","Use one sponge for all rooms","Skip sanitizing tools","Store clean and dirty tools together"]', 0),
(N'cleaning', 6, 2, N'When should a microfiber mop pad be changed?', N'["When visibly soiled or after contaminated areas","Only once a week","Only when it tears","Never during a job"]', 0),
(N'cleaning', 7, 2, N'How should high-touch surfaces be disinfected?', N'["Clean first and allow proper contact time","Wipe quickly and dry immediately","Use water only","Spray from a distance and walk away"]', 0),
(N'cleaning', 8, 2, N'How should vacuum cords be handled during service?', N'["Check for damage and keep away from walk paths","Pull the cord by force","Run over the cord with the vacuum","Leave it stretched across doorways"]', 0),
(N'cleaning', 9, 3, N'What is the purpose of disinfectant contact time?', N'["To let the surface stay wet long enough to work","To make the room smell better only","To skip rinsing","To dry surfaces immediately"]', 0),
(N'cleaning', 10, 3, N'Which cleaning direction is usually best for dusting a room?', N'["Top to bottom","Bottom to top only","Random order","Outside walls first always"]', 0),
(N'cleaning', 11, 3, N'What should you do if you find broken glass?', N'["Use gloves and a proper pickup tool","Sweep with bare hands","Ignore small pieces","Vacuum without inspection"]', 0),
(N'cleaning', 12, 3, N'What is a good first step before starting work in a customer''s home?', N'["Confirm the scope and areas to clean","Start spraying immediately","Move furniture without asking","Skip the walkthrough"]', 0),
(N'cleaning', 13, 4, N'Which flooring surface can be damaged by too much water?', N'["Hardwood flooring","Concrete only","Ceramic tile only","Metal flooring"]', 0),
(N'cleaning', 14, 4, N'What helps reduce streaks when cleaning mirrors?', N'["A clean microfiber cloth and proper glass cleaner","A strong abrasive pad","A dirty towel","Hot bleach solution"]', 0),
(N'cleaning', 15, 4, N'What should be documented after a cleaning job is completed?', N'["Completed tasks, issues found, and notes","Only the payment amount","Only the arrival time","Nothing at all"]', 0),
(N'cleaning', 16, 4, N'If a customer has pets in the home, what is the best practice?', N'["Use pet-safe practices and secure doors or gates","Spray strong chemicals near food bowls","Leave exterior doors open","Ignore pet instructions"]', 0),
(N'cleaning', 17, 5, N'What is the best practice after raw food contamination on a kitchen surface?', N'["Clean first, then disinfect with proper contact time","Use a dry cloth only","Add scented spray only","Skip sanitizing if it looks clean"]', 0),
(N'cleaning', 18, 5, N'How should cleaning chemicals be stored during service?', N'["Labeled and kept secure away from children and pets","In unlabeled bottles","Open on the floor","Mixed together in one container"]', 0),
(N'cleaning', 19, 5, N'What should you do if a stain does not respond to standard treatment?', N'["Stop and inform the customer before aggressive methods","Scrub harder with any chemical","Ignore possible damage","Cut the surface material"]', 0),
(N'cleaning', 20, 5, N'What is the final step before leaving the property?', N'["Do a final walkthrough and confirm satisfaction","Leave without checking","Turn off the water heater","Take all trash bags but skip inspection"]', 0),
(N'landscaping', 1, 1, N'Before using a string trimmer near people, what should be worn first?', N'["Safety glasses and protective gear","Flip-flops","Loose jewelry","No protection is needed"]', 0),
(N'landscaping', 2, 1, N'What is the best first step before mowing a new property?', N'["Walk the site and remove debris","Start mowing immediately","Water the lawn heavily","Trim shrubs first"]', 0),
(N'landscaping', 3, 1, N'Why should grass not be cut too short?', N'["It stresses the turf and weakens roots","It grows faster overnight","It makes mulch unnecessary","It prevents irrigation"]', 0),
(N'landscaping', 4, 1, N'What should be checked before starting a mower?', N'["Fuel, oil, and blade condition","House paint color","Customer Wi-Fi password","Fence stain color"]', 0),
(N'landscaping', 5, 2, N'What is the best time to water most lawns?', N'["Early morning","At noon","Late night","Only after rain"]', 0),
(N'landscaping', 6, 2, N'What is a common sign that irrigation needs adjustment?', N'["Dry spots or runoff","Grass is green","Soil is cool","Wind is low"]', 0),
(N'landscaping', 7, 2, N'Why is spacing important when planting shrubs?', N'["Allows mature growth and airflow","Makes watering impossible","Forces roots upward","Prevents mulch use"]', 0),
(N'landscaping', 8, 2, N'What is a key benefit of mulch?', N'["Helps retain moisture and reduce weeds","Eliminates all watering","Replaces soil","Makes pruning unnecessary"]', 0),
(N'landscaping', 9, 3, N'What is the main purpose of edging?', N'["Creates clean separation lines","Makes grass grow taller","Removes irrigation","Fertilizes soil"]', 0),
(N'landscaping', 10, 3, N'What should be done before applying fertilizer?', N'["Identify turf needs and follow label directions","Apply the maximum amount","Skip the weather check","Water flowers with fuel"]', 0),
(N'landscaping', 11, 3, N'Which tool is best for pruning small shrubs?', N'["Hand pruners","Sledgehammer","Chainsaw for all cuts","Leaf blower"]', 0),
(N'landscaping', 12, 3, N'Why is grading important around a home?', N'["Directs water away from the structure","Traps water near the foundation","Increases roof load","Changes the paint color"]', 0),
(N'landscaping', 13, 4, N'Before repairing a sprinkler head, what should be done first?', N'["Shut off the irrigation zone or water","Add more pressure","Cut the grass first","Ignore the leak"]', 0),
(N'landscaping', 14, 4, N'What is a common sign of overwatering?', N'["Mushy soil and yellowing or fungus","Dry, cracking soil","Strong roots only","Cleaner sidewalks"]', 0),
(N'landscaping', 15, 4, N'Why are base layers important in hardscape work?', N'["They provide stability and drainage","They make plants taller","They replace edging","They eliminate compaction"]', 0),
(N'landscaping', 16, 4, N'What should a provider do if a task is outside their skill or scope?', N'["Inform the customer and decline or refer appropriately","Do it anyway","Hide the issue","Bill extra without explanation"]', 0),
(N'landscaping', 17, 5, N'What is the best way to avoid damage when using a blower near flower beds?', N'["Use low speed and keep the blower away from beds","Use maximum power toward flowers","Aim directly at mulch only","Skip clearing debris"]', 0),
(N'landscaping', 18, 5, N'What is the safest way to lift heavy bags of soil or mulch?', N'["Bend with legs and lift carefully or use a team","Lift with your back only","Throw bags from the truck","Drag bags without lifting"]', 0),
(N'landscaping', 19, 5, N'What is a best customer practice after the job is completed?', N'["Walk the site with the customer and confirm satisfaction","Leave without checking the work","Bill before cleanup","Skip final communication"]', 0),
(N'landscaping', 20, 5, N'If herbicide is used, what is most important?', N'["Follow label directions and use proper PPE","Apply extra for faster results","Mix with any other chemical","Skip protecting nearby plants"]', 0),
(N'pest', 1, 1, N'Before mixing or applying pest control chemicals, what should always be read first?', N'["The product label","The customer invoice","The weather app","The company logo"]', 0),
(N'pest', 2, 1, N'What is the safest first step before treating an interior area?', N'["Identify people, pets, and sensitive areas","Spray immediately","Close all vents permanently","Increase the dosage"]', 0),
(N'pest', 3, 1, N'Which item is basic personal protective equipment for many pest control tasks?', N'["Gloves","Sandals","Loose scarf","Earbuds"]', 0),
(N'pest', 4, 1, N'Why is correct pest identification important?', N'["To choose the right treatment method","To make the job longer","To avoid inspection notes","To skip documentation"]', 0),
(N'pest', 5, 2, N'What should be checked before applying an exterior treatment?', N'["Wind and weather conditions","The neighbor''s mailbox","The paint color","The office playlist"]', 0),
(N'pest', 6, 2, N'Why is measuring chemical correctly important?', N'["To follow label rates safely","To make the smell stronger","To finish the bottle faster","To avoid wearing gloves"]', 0),
(N'pest', 7, 2, N'What is a common sign of a termite problem?', N'["Mud tubes","Bright wall paint","Cold air from vents","Loose doorknob"]', 0),
(N'pest', 8, 2, N'What is the best first step when a customer reports ants in the kitchen?', N'["Inspect and identify the source","Spray every room immediately","Ignore entry points","Turn off the refrigerator"]', 0),
(N'pest', 9, 3, N'Which pest is commonly associated with droppings and gnaw marks?', N'["Rodents","Butterflies","Ladybugs","Dragonflies"]', 0),
(N'pest', 10, 3, N'When treating near food-prep areas, what is most important?', N'["Protect food-contact surfaces","Use extra product","Leave containers open","Skip cleanup"]', 0),
(N'pest', 11, 3, N'What is the purpose of a follow-up visit in pest control?', N'["Check treatment results and activity","Raise the invoice only","Change the company logo","Refill every chemical bottle"]', 0),
(N'pest', 12, 3, N'What should be done with unused mixed chemical when the label gives disposal instructions?', N'["Follow the label disposal instructions","Pour it in any drain","Store it in a soda bottle","Leave it in the truck bed"]', 0),
(N'pest', 13, 4, N'What is one reason to seal or note entry points during service?', N'["To help reduce future pest entry","To increase chemical use","To make walls look darker","To avoid inspections"]', 0),
(N'pest', 14, 4, N'Which tool is commonly used to inspect hard-to-see pest areas?', N'["Flashlight","Television remote","Hair dryer","Paint roller"]', 0),
(N'pest', 15, 4, N'Why should treatment records be completed clearly?', N'["To document work and support safe service","To avoid wearing PPE","To replace the label","To shorten the inspection"]', 0),
(N'pest', 16, 4, N'If a customer has pets, what should the technician do?', N'["Explain safety instructions and reentry guidance","Double the product amount","Ignore the pets","Block the exits"]', 0),
(N'pest', 17, 5, N'What is the best reason to identify the type of cockroach before treatment?', N'["Different species may require different strategies","All roaches live the same way","It changes the company name","It removes the need to inspect"]', 0),
(N'pest', 18, 5, N'What should be done before using application equipment?', N'["Inspect it for leaks or damage","Leave it untested","Remove all labels","Overfill it past the line"]', 0),
(N'pest', 19, 5, N'What is one key part of good customer communication after service?', N'["Explain what was found and next steps","Say nothing and leave","Hide service notes","Promise impossible results"]', 0),
(N'pest', 20, 5, N'What does passing the INDOR pest control exam allow the provider to unlock?', N'["Pest control jobs only","All provider categories","Banking access","Unlimited free ads"]', 0),
(N'appliance', 1, 1, N'What should be done first before servicing any appliance?', N'["Disconnect power","Replace parts","Remove panels","Test the motor"]', 0),
(N'appliance', 2, 1, N'What is the purpose of a multimeter in appliance repair?', N'["Measure voltage and continuity","Lift heavy appliances","Clean internal parts","Seal refrigerant lines"]', 0),
(N'appliance', 3, 1, N'If a dryer does not heat, which component is commonly checked first?', N'["Heating element","Water valve","Door handle","Ice maker arm"]', 0),
(N'appliance', 4, 1, N'Why is it important to verify the model number before ordering parts?', N'["To match the correct replacement part","To increase water pressure","To reduce cleaning time","To bypass diagnostics"]', 0),
(N'appliance', 5, 2, N'A refrigerator is running but not cooling well. What should be checked first?', N'["Condenser coils","Cabinet color","Door logo","Control knob shape"]', 0),
(N'appliance', 6, 2, N'What does continuity testing help confirm?', N'["Whether a circuit path is complete","Whether the appliance is level","Whether the paint is dry","Whether the customer approved the repair"]', 0),
(N'appliance', 7, 2, N'If a washer does not drain, which part is commonly inspected?', N'["Drain pump","Bake element","Water filter pitcher","Light bulb socket"]', 0),
(N'appliance', 8, 2, N'Why should the correct replacement part number be used?', N'["To ensure proper fit and function","To reduce floor noise","To improve packaging","To speed up cleaning only"]', 0),
(N'appliance', 9, 3, N'What is a common sign of a faulty refrigerator door gasket?', N'["Warm air leaking around the door","The shelves are full","The cord is too long","The ice tray is blue"]', 0),
(N'appliance', 10, 3, N'When diagnosing an electric oven that will not heat, what is commonly checked?', N'["Bake element","Door paint","Handle screws only","Rack color"]', 0),
(N'appliance', 11, 3, N'What is the function of a thermal fuse in many appliances?', N'["Protect against overheating","Increase water pressure","Change motor speed automatically","Improve exterior appearance"]', 0),
(N'appliance', 12, 3, N'If a dishwasher is not filling with water, which item is often checked first?', N'["Water inlet valve","Dryer vent","Cabinet feet","Door sticker"]', 0),
(N'appliance', 13, 4, N'Why is it important to inspect appliance wiring for damage?', N'["To prevent shorts and unsafe operation","To improve shelf appearance","To increase detergent flow","To reduce packaging waste"]', 0),
(N'appliance', 14, 4, N'A microwave is completely dead. What is one basic item to verify first?', N'["Power supply to the unit","Color of the control panel","Shape of the glass tray","Position of the kitchen table"]', 0),
(N'appliance', 15, 4, N'What does a technician use a wiring diagram for?', N'["To trace circuits and components","To estimate appliance weight","To clean the appliance exterior","To advertise services"]', 0),
(N'appliance', 16, 4, N'If a dryer tumbles but has weak airflow, what is a common cause?', N'["Blocked venting","Loose cabinet paint","Wrong timer font","Cold water valve leak"]', 0),
(N'appliance', 17, 5, N'Why should moving parts be inspected for wear?', N'["To prevent failure and noise","To speed up packaging","To brighten the appliance finish","To increase room lighting"]', 0),
(N'appliance', 18, 5, N'What is a common first step when troubleshooting an appliance complaint?', N'["Verify the reported symptom","Order parts without testing","Replace the control board immediately","Ignore the customer description"]', 0),
(N'appliance', 19, 5, N'What customer service practice is most important after completing a repair?', N'["Explain the repair and test results","Hide replaced parts","Leave without speaking","Skip cleanup"]', 0),
(N'appliance', 20, 5, N'What should be done before closing the job?', N'["Confirm the appliance operates correctly","Remove the serial tag","Turn off the house water main","Reset unrelated appliances"]', 0);
GO

-- Human-readable answer key (correct option text per question)
IF OBJECT_ID(N'dbo.vw_IndorProveedorExamAnswerKey', N'V') IS NOT NULL
    DROP VIEW dbo.vw_IndorProveedorExamAnswerKey;
GO

CREATE VIEW dbo.vw_IndorProveedorExamAnswerKey
AS
SELECT
    p.TradeCode,
    p.QuestionNumber,
    p.PageNumber,
    p.TextEn AS QuestionText,
    p.CorrectIndex,
    CASE p.CorrectIndex
        WHEN 0 THEN JSON_VALUE(p.OptionsJson, '$[0]')
        WHEN 1 THEN JSON_VALUE(p.OptionsJson, '$[1]')
        WHEN 2 THEN JSON_VALUE(p.OptionsJson, '$[2]')
        WHEN 3 THEN JSON_VALUE(p.OptionsJson, '$[3]')
    END AS CorrectAnswerText,
    p.OptionsJson,
    p.Activo
FROM dbo.IndorProveedorExamPreguntas p;
GO

DECLARE @QuestionCount INT = (SELECT COUNT(*) FROM dbo.IndorProveedorExamPreguntas);
DECLARE @TradeCount INT = (SELECT COUNT(DISTINCT TradeCode) FROM dbo.IndorProveedorExamPreguntas);
PRINT CONCAT('Seeded ', @QuestionCount, ' exam questions across ', @TradeCount, ' trades.');
GO

-- Quick verification: list answer key summary by trade
SELECT TradeCode, COUNT(*) AS QuestionCount,
       MIN(CorrectIndex) AS MinCorrectIndex, MAX(CorrectIndex) AS MaxCorrectIndex
FROM dbo.IndorProveedorExamPreguntas
GROUP BY TradeCode
ORDER BY TradeCode;
GO
